apiVersion: v1
kind: Service
metadata:
  name: svc-web-signup
  namespace: web
spec:
  type: NodePort
  clusterIP: 172.20.20.40
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30200
  selector:
    app: web-signup
