apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-order
  namespace: was
  annotations:
    kubernetes.io/change-cause: was-order:v1.2
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: was-order
  template:
    metadata:
      labels:
        app: was-order
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - was-order
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: was-order
      containers:
      - image: soonge97/was-order-nojsp:v1.0
        name: was-order
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 250m
            memory: 250Mi
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/local/tomcat/webapps/ROOT/ # 볼륨마운트 경로
      volumes:
      - name: persistent-storage  # 볼륨이름
        persistentVolumeClaim:
          claimName: pvc-was-order  # PVC를 참조
