apiVersion: v1
kind: Service
metadata:
  name: svc-web-main
  namespace: web
spec:
  type: NodePort
  clusterIP: 172.20.20.20
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
  selector:
    app: web-main
